name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 8,20 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Compile Sources
        run: mvn clean compiler:compile compiler:testCompile -f pom.xml

      - name: Run Tests
        env:
          API_KEY: ${{ secrets.TESTS_API_KEY }}
        run: mvn surefire:test -f pom.xml
